[toolchain]
anchor_version = "1.0.2"

[features]
seeds = false
skip-lint = false

[programs.localnet]
cryptoseeds_protocol = "5RWpGEGB9Yr7cmaoWZJQ9t263Wb8K18GrcMDqHByLXSb"

[programs.devnet]
cryptoseeds_protocol = "5RWpGEGB9Yr7cmaoWZJQ9t263Wb8K18GrcMDqHByLXSb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/cryptoseeds_protocol/Cargo.toml"
